### ISSUE TITLE
Improvement: PF400 Location and Rotation

### ISSUE THREAD

**Issue by RyanTheRobothead** [AD-SDL/pf400_module#10]
## Requirements

- Support a location configuration file (`locations.yaml`)
- CLI Arg pointing to locations configuration file `--locations <path/to/locations.yaml>`

```
locations:
  a:
    joint_angles: x, y, z, r, p, y
    safe_approach_path: # Optional
      - b
      - c
    orientation: narrow/wide
  b: ...
  c: ...
  rotation_narrow: ...
  rotation_wide: ...
rotation_location:
  narrow: rotation_narrow
  wide: rotation_wide
```

- `PF400Location` Pydantic DataClass
- Read locations from locations.yaml on startup
- Support named location lookup in addition to pure joint angles (transfer source/target, etc.)
- Validate incoming strings against named locations
- Remove pf400 joint angles from workcell definitions
- Add support for safe approach path in transfer/pick/place (read from dict, pass to driver func)
